# Generated by Django 4.2.1 on 2023-06-26 06:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('code', ckeditor.fields.RichTextField(verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.category')),
            ],
            options={
                'verbose_name': 'Código',
                'ordering': ('language', 'category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='code/image/', verbose_name='Imagen')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.code')),
            ],
            options={
                'verbose_name': 'Imagen de Código',
                'verbose_name_plural': 'Imágenes de Código',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.language'),
        ),
    ]
